from .animation import Animation
from .audio import Audio
from .botcommand import BotCommand
from .botcommandscope import BotCommandScope
from .botcommandscopeallprivatechats import BotCommandScopeAllPrivateChats
from .botcommandscopechat import BotCommandScopeChat
from .botcommandscopedefault import BotCommandScopeDefault
from .callbackquery import CallbackQuery
from .chat import Chat
from .chatlocation import ChatLocation
from .chatpermissions import ChatPermissions
from .chatphoto import ChatPhoto
from .contact import Contact
from .dice import Dice
from .document import Document
from .file import File
from .forcereply import ForceReply
from .inlinekeyboardbutton import InlineKeyboardButton
from .inlinekeyboardmarkup import InlineKeyboardMarkup
from .inputfile import InputFile
from .inputmediaanimation import InputMediaAnimation
from .inputmediaaudio import InputMediaAudio
from .inputmediadocument import InputMediaDocument
from .inputmediaphoto import InputMediaPhoto
from .inputmediavideo import InputMediaVideo
from .keyboardbutton import KeyboardButton
from .location import Location
from .maskposition import MaskPosition
from .message import Message
from .messageentity import MessageEntity
from .messageid import MessageId
from .photosize import PhotoSize
from .replykeyboardmarkup import ReplyKeyboardMarkup
from .replykeyboardremove import ReplyKeyboardRemove
from .responseparameters import ResponseParameters
from .sticker import Sticker
from .stickerset import StickerSet
from .update import Update
from .user import User
from .userprofilephotos import UserProfilePhotos
from .video import Video
from .videonote import VideoNote
from .voice import Voice
from .webhookinfo import WebhookInfo
